name: Continuous Integration (CI)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  integration:
    name: CI (lint, text, build)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for semantic-release to analyze

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
      
      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: pnpm run test:once

      - name: Build library
        run: pnpm run build
