name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write        # allow creating tags & releases
  packages: write        # allow publishing packages to GitHub Packages
  issues: write          # optional: to let semantic-release comment on issues
  pull-requests: write   # optional
  id-token: write        # optional; needed if using OIDC for npm provenance

jobs:
  ci:
    name: CI (Lint, Test, Build)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for semantic-release to analyze

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
      
      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: pnpm run test:once

      - name: Build library
        run: pnpm run build

  release:
    name: Release
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for semantic-release to analyze

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com' # Configure npm to use the GitHub Package Registry
          scope: '@devdado'    # important: matches package scope

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Publish to GitHub Registry via semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # used by npm client to auth to GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # used by @semantic-release/github
        run: pnpm exec semantic-release
