name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and write to the repository
      packages: write # Needed to publish to the GitHub Package Registry
      id-token: write # Add this to allow Semantic Release to create a new tag
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for semantic-release to analyze

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          registry-url: 'https://registry.npmjs.org' # Explicitly set the registry for dependency installation

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test:once

      - name: Build project
        run: pnpm run build

      - name: Semantic Release
        id: semantic
        run: pnpm exec semantic-release

      - name: Publish to GitHub Packages
        if: steps.semantic.outputs.new-version
        run: pnpm publish --registry=https://npm.pkg.github.com